// <auto-generated />
using System;
using Commerce.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Commerce.Repositories.Migrations
{
    [DbContext(typeof(CommerceDbContext))]
    [Migration("20260124203931_SeedCategoriesAndProducts")]
    partial class SeedCategoriesAndProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commerce.Repositories.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic gadgets and devices",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Various kinds of books and literature",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Appliances and tools for home and kitchen",
                            IsActive = true,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's and women's apparel",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sports gear and outdoor equipment",
                            IsActive = true,
                            Name = "Sports & Outdoors"
                        });
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest model smartphone with advanced features",
                            IsActive = true,
                            Name = "Smartphone",
                            Price = 699.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 1002,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise-canceling over-ear headphones",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Price = 199.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 1003,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight laptop for work and entertainment",
                            IsActive = true,
                            Name = "Laptop",
                            Price = 1199.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 2001,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A Handbook of Agile Software Craftsmanship",
                            IsActive = true,
                            Name = "Clean Code",
                            Price = 34.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2002,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Your journey to mastery",
                            IsActive = true,
                            Name = "The Pragmatic Programmer",
                            Price = 39.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 2003,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elements of reusable object-oriented software",
                            IsActive = true,
                            Name = "Design Patterns",
                            Price = 49.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 3001,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oil-free air fryer with multiple presets",
                            IsActive = true,
                            Name = "Air Fryer",
                            Price = 129.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 3002,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-speed blender for smoothies and soups",
                            IsActive = true,
                            Name = "Blender",
                            Price = 89.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3003,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "12-cup programmable coffee maker",
                            IsActive = true,
                            Name = "Coffee Maker",
                            Price = 79.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 4001,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% cotton men's t-shirt",
                            IsActive = true,
                            Name = "Men's T-Shirt",
                            Price = 19.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 4002,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slim fit women's jeans",
                            IsActive = true,
                            Name = "Women's Jeans",
                            Price = 49.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 4003,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unisex fleece hoodie",
                            IsActive = true,
                            Name = "Hoodie",
                            Price = 39.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 5001,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip yoga mat",
                            IsActive = true,
                            Name = "Yoga Mat",
                            Price = 29.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 5002,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable dumbbell set",
                            IsActive = true,
                            Name = "Dumbbell Set",
                            Price = 99.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 5003,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "4-person waterproof camping tent",
                            IsActive = true,
                            Name = "Camping Tent",
                            Price = 149.99m,
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.Product", b =>
                {
                    b.HasOne("Commerce.Repositories.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
