// <auto-generated />
using System;
using Commerce.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Commerce.Repositories.Migrations
{
    [DbContext(typeof(CommerceDbContext))]
    [Migration("20260207180222_ReassignProductsToChildCategories")]
    partial class ReassignProductsToChildCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commerce.Repositories.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic gadgets and devices",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Various kinds of books and literature",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Appliances and tools for home and kitchen",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's and women's apparel",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sports gear and outdoor equipment",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Desktops, laptops, components",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable computers",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's clothing",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's clothing",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Women"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Shirts & tops",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Shirts"
                        });
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.CategoryLink", b =>
                {
                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ChildCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("ParentCategoryId", "ChildCategoryId");

                    b.HasIndex("ChildCategoryId");

                    b.ToTable("CategoryLink", null, t =>
                        {
                            t.HasCheckConstraint("CK_CategoryLink_NoSelfLink", "\"ParentCategoryId\" <> \"ChildCategoryId\"");
                        });

                    b.HasData(
                        new
                        {
                            ParentCategoryId = 1,
                            ChildCategoryId = 6
                        },
                        new
                        {
                            ParentCategoryId = 6,
                            ChildCategoryId = 7
                        },
                        new
                        {
                            ParentCategoryId = 4,
                            ChildCategoryId = 8
                        },
                        new
                        {
                            ParentCategoryId = 4,
                            ChildCategoryId = 9
                        },
                        new
                        {
                            ParentCategoryId = 8,
                            ChildCategoryId = 10
                        },
                        new
                        {
                            ParentCategoryId = 9,
                            ChildCategoryId = 10
                        });
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.EntityTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("EntityTranslation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dispositivos y aparatos electrónicos",
                            EntityId = 1,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Varios tipos de libros y literatura",
                            EntityId = 2,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Libros"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Electrodomésticos y herramientas para el hogar y la cocina",
                            EntityId = 3,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Hogar y Cocina"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ropa para hombres y mujeres",
                            EntityId = 4,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Ropa"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Equipamiento deportivo y para actividades al aire libre",
                            EntityId = 5,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Deportes y Aire Libre"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Escritorios, portátiles, componentes",
                            EntityId = 6,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Computadoras"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Computadoras portátiles",
                            EntityId = 7,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Portátiles"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ropa de hombres",
                            EntityId = 8,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Hombres"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ropa de mujeres",
                            EntityId = 9,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Mujeres"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Camisas y blusas",
                            EntityId = 10,
                            EntityType = "Category",
                            LanguageCode = "es",
                            Name = "Camisas"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Último modelo de teléfono inteligente con funciones avanzadas",
                            EntityId = 1001,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Teléfono Inteligente"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Auriculares supraaurales con cancelación de ruido",
                            EntityId = 1002,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Auriculares Inalámbricos"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Portátil ligero para trabajo y entretenimiento",
                            EntityId = 1003,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Portátil"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Manual de desarrollo de software ágil",
                            EntityId = 2001,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Código Limpio"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Tu camino hacia la maestría",
                            EntityId = 2002,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "El Programador Pragmático"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Elementos de software orientado a objetos reutilizable",
                            EntityId = 2003,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Patrones de Diseño"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Freidora de aire sin aceite con múltiples preajustes",
                            EntityId = 3001,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Freidora de Aire"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Licuadora de alta velocidad para batidos y sopas",
                            EntityId = 3002,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Licuadora"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Cafetera programable de 12 tazas",
                            EntityId = 3003,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Cafetera"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Camiseta de hombre 100% algodón",
                            EntityId = 4001,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Camiseta de Hombre"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Jeans ajustados de mujer",
                            EntityId = 4002,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Jeans de Mujer"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Sudadera con capucha unisex de forro polar",
                            EntityId = 4003,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Sudadera con Capucha"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Esterilla de yoga antideslizante",
                            EntityId = 5001,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Esterilla de Yoga"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Juego de mancuernas ajustables",
                            EntityId = 5002,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Juego de Mancuernas"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Tienda de campaña impermeable para 4 personas",
                            EntityId = 5003,
                            EntityType = "Product",
                            LanguageCode = "es",
                            Name = "Tienda de Campaña"
                        });
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("Type", "OwnerId");

                    b.HasIndex("Type", "OwnerId", "DisplayOrder");

                    b.ToTable("ImageAssets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1001-1001-1001-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "smartphone.webp",
                            IsPrimary = true,
                            ObjectKey = "products/1001/smartphone.webp",
                            OwnerId = 1001,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa1111-1002-1002-1002-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "headphones.webp",
                            IsPrimary = true,
                            ObjectKey = "products/1002/headphones.webp",
                            OwnerId = 1002,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa1111-1003-1003-1003-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "laptop.webp",
                            IsPrimary = true,
                            ObjectKey = "products/1003/laptop.webp",
                            OwnerId = 1003,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2001-2001-2001-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "clean-code.webp",
                            IsPrimary = true,
                            ObjectKey = "products/2001/clean-code.webp",
                            OwnerId = 2001,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2002-2002-2002-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "pragmatic-programmer.webp",
                            IsPrimary = true,
                            ObjectKey = "products/2002/pragmatic-programmer.webp",
                            OwnerId = 2002,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2003-2003-2003-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "design-patterns.webp",
                            IsPrimary = true,
                            ObjectKey = "products/2003/design-patterns.webp",
                            OwnerId = 2003,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa3333-3001-3001-3001-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "air-fryer.webp",
                            IsPrimary = true,
                            ObjectKey = "products/3001/air-fryer.webp",
                            OwnerId = 3001,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa3333-3002-3002-3002-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "blender.webp",
                            IsPrimary = true,
                            ObjectKey = "products/3002/blender.webp",
                            OwnerId = 3002,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa3333-3003-3003-3003-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "coffee-maker.webp",
                            IsPrimary = true,
                            ObjectKey = "products/3003/coffee-maker.webp",
                            OwnerId = 3003,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa4444-4001-4001-4001-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "tshirt.webp",
                            IsPrimary = true,
                            ObjectKey = "products/4001/tshirt.webp",
                            OwnerId = 4001,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa4444-4002-4002-4002-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "jeans.webp",
                            IsPrimary = true,
                            ObjectKey = "products/4002/jeans.webp",
                            OwnerId = 4002,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa4444-4003-4003-4003-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "hoodie.webp",
                            IsPrimary = true,
                            ObjectKey = "products/4003/hoodie.webp",
                            OwnerId = 4003,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa5555-5001-5001-5001-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "yoga-mat.webp",
                            IsPrimary = true,
                            ObjectKey = "products/5001/yoga-mat.webp",
                            OwnerId = 5001,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa5555-5002-5002-5002-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "dumbbell-set.webp",
                            IsPrimary = true,
                            ObjectKey = "products/5002/dumbbell-set.webp",
                            OwnerId = 5002,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa5555-5003-5003-5003-000000000001"),
                            ContentType = "image/webp",
                            DisplayOrder = 0,
                            FileName = "camping-tent.webp",
                            IsPrimary = true,
                            ObjectKey = "products/5003/camping-tent.webp",
                            OwnerId = 5003,
                            SizeBytes = 50000L,
                            Type = "Product",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000001"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 0,
                            FileName = "elec1.jpg",
                            IsPrimary = true,
                            ObjectKey = "categories/1/elec1.jpg",
                            OwnerId = 1,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000002"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 1,
                            FileName = "elec2.jpg",
                            IsPrimary = false,
                            ObjectKey = "categories/1/elec2.jpg",
                            OwnerId = 1,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000003"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 2,
                            FileName = "elec3.jpg",
                            IsPrimary = false,
                            ObjectKey = "categories/1/elec3.jpg",
                            OwnerId = 1,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-0002-0002-0002-000000000001"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 0,
                            FileName = "dariuszsankowski-glasses-1052023_640.jpg",
                            IsPrimary = true,
                            ObjectKey = "categories/2/dariuszsankowski-glasses-1052023_640.jpg",
                            OwnerId = 2,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-0002-0002-0002-000000000002"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 1,
                            FileName = "dglodowska-book-419589_640.jpg",
                            IsPrimary = false,
                            ObjectKey = "categories/2/dglodowska-book-419589_640.jpg",
                            OwnerId = 2,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000001"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 0,
                            FileName = "kitchen1.jpg",
                            IsPrimary = true,
                            ObjectKey = "categories/3/kitchen1.jpg",
                            OwnerId = 3,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000002"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 1,
                            FileName = "kitchen2.jpg",
                            IsPrimary = false,
                            ObjectKey = "categories/3/kitchen2.jpg",
                            OwnerId = 3,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000003"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 2,
                            FileName = "kitchen3.jpg",
                            IsPrimary = false,
                            ObjectKey = "categories/3/kitchen3.jpg",
                            OwnerId = 3,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0004-0004-0004-0004-000000000001"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 0,
                            FileName = "cloth1.jpg",
                            IsPrimary = true,
                            ObjectKey = "categories/4/cloth1.jpg",
                            OwnerId = 4,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0004-0004-0004-0004-000000000002"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 1,
                            FileName = "cloth2.jpg",
                            IsPrimary = false,
                            ObjectKey = "categories/4/cloth2.jpg",
                            OwnerId = 4,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0004-0004-0004-0004-000000000003"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 2,
                            FileName = "cloth3.jpg",
                            IsPrimary = false,
                            ObjectKey = "categories/4/cloth3.jpg",
                            OwnerId = 4,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0004-0004-0004-0004-000000000004"),
                            ContentType = "image/jpeg",
                            DisplayOrder = 3,
                            FileName = "cloth4.jpg",
                            IsPrimary = false,
                            ObjectKey = "categories/4/cloth4.jpg",
                            OwnerId = 4,
                            SizeBytes = 50000L,
                            Type = "Category",
                            UploadedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest model smartphone with advanced features",
                            IsActive = true,
                            Name = "Smartphone",
                            Price = 699.99m,
                            SalePrice = 599.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 1002,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise-canceling over-ear headphones",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Price = 199.99m,
                            SalePrice = 149.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 1003,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight laptop for work and entertainment",
                            IsActive = true,
                            Name = "Laptop",
                            Price = 1199.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 2001,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A Handbook of Agile Software Craftsmanship",
                            IsActive = true,
                            Name = "Clean Code",
                            Price = 34.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2002,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Your journey to mastery",
                            IsActive = true,
                            Name = "The Pragmatic Programmer",
                            Price = 39.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 2003,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elements of reusable object-oriented software",
                            IsActive = true,
                            Name = "Design Patterns",
                            Price = 49.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 3001,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oil-free air fryer with multiple presets",
                            IsActive = true,
                            Name = "Air Fryer",
                            Price = 129.99m,
                            SalePrice = 99.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 3002,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-speed blender for smoothies and soups",
                            IsActive = true,
                            Name = "Blender",
                            Price = 89.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3003,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "12-cup programmable coffee maker",
                            IsActive = true,
                            Name = "Coffee Maker",
                            Price = 79.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 4001,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% cotton men's t-shirt",
                            IsActive = true,
                            Name = "Men's T-Shirt",
                            Price = 19.99m,
                            SalePrice = 14.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 4002,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slim fit women's jeans",
                            IsActive = true,
                            Name = "Women's Jeans",
                            Price = 49.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 4003,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unisex fleece hoodie",
                            IsActive = true,
                            Name = "Hoodie",
                            Price = 39.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 5001,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip yoga mat",
                            IsActive = true,
                            Name = "Yoga Mat",
                            Price = 29.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 5002,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable dumbbell set",
                            IsActive = true,
                            Name = "Dumbbell Set",
                            Price = 99.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 5003,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "4-person waterproof camping tent",
                            IsActive = true,
                            Name = "Camping Tent",
                            Price = 149.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 9001,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test product without seeded images",
                            IsActive = true,
                            Name = "Test Product 1",
                            Price = 10.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 9002,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test product without seeded images",
                            IsActive = true,
                            Name = "Test Product 2",
                            Price = 20.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 9003,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test product without seeded images",
                            IsActive = true,
                            Name = "Test Product 3",
                            Price = 30.00m,
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.CategoryLink", b =>
                {
                    b.HasOne("Commerce.Repositories.Entities.Category", "ChildCategory")
                        .WithMany("ParentLinks")
                        .HasForeignKey("ChildCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Commerce.Repositories.Entities.Category", "ParentCategory")
                        .WithMany("ChildLinks")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildCategory");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.Product", b =>
                {
                    b.HasOne("Commerce.Repositories.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Commerce.Repositories.Entities.Category", b =>
                {
                    b.Navigation("ChildLinks");

                    b.Navigation("ParentLinks");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
